### ISSUE TITLE
Entity templates > Blocks attach support

### ISSUE THREAD

**Issue by quyenbui** [atdrupal/at_base.module#133]
``` yml
entity_templates:
  node:
    blog:
      full:
        template: '@crom_quyen/templates/Nodes/Blog-full.html.twig'
        blocks:
          cromt:
            content_top:
              - 'at_base:crom_quyen|blog_view_single_header_image'
```
