### ISSUE TITLE
Drupal block > Dynamic variables Can't run as callback

### ISSUE THREAD

**Issue by quyenbui** [atdrupal/at_base.module#149]
I'm still see this problem again.
I'm hope:

``` yml
....
variables:
  - varname: callback
  - varname1: callback1
....
```

varname and varname1 will have been assign value of callback return

actual: varname and varname1 return caback function name as string, not execute
