### ISSUE TITLE
Display blank page when use: template_string: ' '

### ISSUE THREAD

**Issue by phuong-bui-88** [atdrupal/at_base.module#169]
``` yml
routes:
  home:
    title: Home Page
    access arguments: ['access content']
    template_string: ' '
```
