### ISSUE TITLE
drush atr: Support working-copy option

### ISSUE THREAD

**Issue by and1truong** [atdrupal/at_base.module#178]
This should be fixed before #176 

``` yml
projects:
  my_lib:
    type: library
    download: {…}
    working-copy: true
```
