### ISSUE TITLE
Twig filter > rimg (Responsive Image)

### ISSUE THREAD

**Issue by and1truong** [atdrupal/at_base.module#187]
Render an image (internal only):

``` twig
{{ image_path|rimg(profile_name) }}
```

Render profile

``` yaml
# File: /path/to/my_module/config/responsive-images.yml
responsive-images:
    slider_image:
      screens:
        mobile: { max: 320px, style: mobile_image_stlyle }
        tablet: { min: 321px, max: 800px, style: mobile_image_style }
        desktop: { min: 811: style: desktop_image_style }
      fallback: mobile
```
