### ISSUE TITLE
helper.content_render: Support prefix, suffix

### ISSUE THREAD

**Issue by and1truong** [atdrupal/at_base.module#191]
In many cases, we need same data logic for parts of application. Just need a wrapper, so that's why we need suffix and prefix option.
### Tasks
- [ ] Test case
- [ ] Implement
- [ ] Documentation
### Sample data

``` yaml
data:
  prefix: '<div class="header">'
  content: 'Just string'
  prefix: '</div><!-- footer -->'
```
### References
- Background of helper.data_render, read this http://v3k.net/en/at_base/helper.content_render
- https://github.com/atdrupal/at_base/blob/dev-master/lib/Drupal/at_base/Tests/Unit/ServiceContentRenderTest.php
