### ISSUE TITLE
helper.data_render: Support conditions option

### ISSUE THREAD

**Issue by and1truong** [atdrupal/at_base.module#194]
If one of condition callback return FALSE, do not process the data callback.
### Tasks
- [ ] Test case
- [ ] Implement
- [ ] Documentation
### Sample data

``` yml
data_1:
  conditions: ['function_callback']
  content: '{{ "I am Quyen Lun" }}'
data_2:
  conditions:
    - ['function_callback', [a1, a2, a3]]
    - [Quyen_Lun, 'method', [a1, a2, a3]]
    - '@quen_lun:method'
    - ['@quen_rat_lun:method', [a1, a2]]
  template: '@quyen_lun/templates/haizz.html.twig'
data_3:
  conditions: ['function_callback']
  function: 'render_callback'
```
### References
- Background of helper.data_render, read this http://v3k.net/en/at_base/helper.content_render
- https://github.com/atdrupal/at_base/blob/dev-master/lib/Drupal/at_base/Tests/Unit/ServiceContentRenderTest.php
