### ISSUE TITLE
Support delete tags on specific events

### ISSUE THREAD

**Issue by and1truong** [atdrupal/at_base.module#2]
``` yaml
# module_name/config/cache_warming.yml
tags:
  entity_update: ['my_listing:%entity_type', '%entity_type:%entity_id']
  entity_delete: []
  user_login: []
  user_logout: []
```

Later, we will support menu, menu_item, …
