### ISSUE TITLE
Support terminate

### ISSUE THREAD

**Issue by and1truong** [atdrupal/at_base.module#20]
``` yaml
routes:
  controlle: [X, x]
  termiate:
  - function_name
  - 'Class_Name::staticMethod'
  - ['anyCallable']
```

``` php
at_container('terminator')->add($closure);
at_container('terminator')->execute();
```
- Provide custom delivery callback (hook_menu > item > delivery callback)
- Call termiate if it's registered.

Should also check option to integrate HttpFoundation, HttpKernel.
### Reference
- [ajax_deliver](https://api.drupal.org/api/drupal/includes%21ajax.inc/function/ajax_deliver/7)
- [drupal_deliver_html_page](https://api.drupal.org/api/drupal/includes%21common.inc/function/drupal_deliver_html_page/7)
- [image_style_deliver](https://api.drupal.org/api/drupal/modules%21image%21image.module/function/image_style_deliver/7)
- http://docs.guzzlephp.org/en/latest/plugins/async-plugin.html
