### ISSUE TITLE
Config: Support include @include

### ISSUE THREAD

**Issue by and1truong** [atdrupal/at_base.module#203]
1. http://framework.zend.com/manual/2.3/en/modules/zend.config.reader.html#zend-config-reader-yaml
2. https://github.com/zendframework/Component_ZendConfig/blob/master/Reader/Yaml.php#L142

``` yaml
routes:
  hello:
    @include: base.yml
```
