### ISSUE TITLE
Autoload incorrect with directory name begin with n

### ISSUE THREAD

**Issue by sanglt** [atdrupal/at_base.module#224]
Example we have module name nra

The router define:

``` yaml
controller:
      - 'Drupal\nra\Controllers\Node\AddEmployee'
The loader will looking at: Drupal ra\Controllers\Node\AddEmployee
```

If we change to - `Drupal\\nra\Controllers\Node\AddEmployee` it just looking at '/var/aegir/platforms/d728//lib/Controllers/Node/AddEmployee.php' (Skip the module folder name)
