### ISSUE TITLE
Route: Support header option

### ISSUE THREAD

**Issue by and1truong** [atdrupal/at_base.module#232]
``` yaml
foo:
  title: Title
  content: '{ "foo": "bar" }'
  headers:
    'content-type': 'application/json'
```
