### ISSUE TITLE
Route: Support groups

### ISSUE THREAD

**Issue by and1truong** [atdrupal/at_base.module#233]
``` yaml
# my_module/config/routes.yaml

routes: []
groups:
  prefix: myspace
  access: …
  before: …
  headers: …
  attached: …
  routes:
    foo:
      title: Foo
      content: Foo content
    bar:
      title: Bar:
      content: Bar content
```
