### ISSUE TITLE
Assets Management

### ISSUE THREAD

**Issue by and1truong** [atdrupal/at_base.module#25]
``` yaml
assets:
  global_style:
    target: %theme/style/style.css
    filters:
      sass:
        filter: Phalcon\Assets\Filters\Compass
        config: '@module_name/misc/sass/config/%environment/config.ru'
    resources:
      - '@module_name/misc/sass/*.scss'
```

To compile assets:

```
drush at-asset-compile # compile all
drush at-asset-compile global_style # compile specific asset
```
### Ref
- http://docs.phalconphp.com/en/latest/reference/assets.html
