### ISSUE TITLE
Features — Hook collection

### ISSUE THREAD

**Issue by and1truong** [atdrupal/at_base.module#3]
Module can use features.yml to define features:

``` yaml
# module_name/config/features.yml
features:
  my_awesome_feature:
    hooks:
      HOOK_init:
        description: This is my awesome feature
        controller: \Drupal\module_name\Hook\Init
    cache_warming:
      entity_update: ['my_listing:%entity_type', '%entity_type:%entity_id']
    # Need at_route.module
    routes:
      imports:
        - { resource: my_awesome_feature/routes.yml, attributes: routes }
  my_misc_feature:
    hooks:
      HOOK_init:
        description: 'This is misc thing, remove later'
        # This should be called before my_awesome_feature.HOOK_init
        weight: -10
```
### Benefits:
- Code is super clean
- Make the features self documented
- Make is easier for coming module — at_merge.module
