### ISSUE TITLE
Route > Support caching

### ISSUE THREAD

**Issue by and1truong** [atdrupal/at_base.module#43]
``` yaml
routes:
  path:
    title: Hello
    access arguments: ['access content']
    template_string: 'Hi there!'
    cache: 
      type: DRUPAL_CACHE_PER_ROLE
      bin: cache
      ttl: '+ 2 hours'
      tags: [tag 1, tag 2]
```
