### ISSUE TITLE
Cache warming: Support views

### ISSUE THREAD

**Issue by and1truong** [atdrupal/at_base.module#8]
This is continue of #2.

``` yaml
# module_name/config/cache_warming.yml
tags:
  entity_update: ['views:view_name_1', 'views:view_name_2:display_id']
```
