### ISSUE TITLE
Twig Filter > drupalView > Support template

### ISSUE THREAD

**Issue by and1truong** [atdrupal/at_base.module#86]
``` yaml
{% set o = {
        display_id: 'default', 
        template: '@atest_base/templates/views/atest_theming_user.html.twig' } %}
{{ 'atest_theming_user' | drupalView(o) }}

```
