### ISSUE TITLE
Cache warming: Support related taxonomy-terms

### ISSUE THREAD

**Issue by and1truong** [atdrupal/at_base.module#94]
``` yaml
# File: @my_module/config/cache_warming.yml
tags:
  entity_update: ['%entity_type:%taxonomy_terms']
```
