### ISSUE TITLE
Cache warming: Support related relationships (relation.module)

### ISSUE THREAD

**Issue by and1truong** [atdrupal/at_base.module#95]
``` yaml
# File: @my_module/config/cache_warming.yml
tags:
  entity_update: ['%entity_type:%relationships']
```
