### ISSUE TITLE
Cache warming: Support related entity reference (Entity Reference field)

### ISSUE THREAD

**Issue by and1truong** [atdrupal/at_base.module#96]
``` yaml
# File: @my_module/config/cache_warming.yml
tags:
  entity_update: ['%entity_type:%entity_references']
```
