### ISSUE TITLE
Cache warming: Support %uid token

### ISSUE THREAD

**Issue by and1truong** [atdrupal/at_base.module#97]
``` yaml
# File: @my_module/config/cache_warming.yml
tags:
  entity_update: ['%entity_type:%uid']
```

Reference 
1. Doc http://v3k.net/en/at_base/caching
2. Test cases: https://github.com/atdrupal/at_base/blob/dev-master/lib/Drupal/at_base/Tests/Unit/CacheTest.php
