### ISSUE TITLE
Cache warming: Support %roles token

### ISSUE THREAD

**Issue by and1truong** [atdrupal/at_base.module#98]
``` yaml
# File: @my_module/config/cache_warming.yml
tags:
  entity_update: ['%entity_type:%roles']
```
